name: CI

on:
    push:
      branches:
        - main
        - master
      tags:
        - '*'
    pull_request:
    workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist/
  
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install module
        run: |
          pip install .

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d
      
      - name: Wait for containers to start
        run: python ./CI/wait_for_server.py

      - name: Run tests
        run: hatch test

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .coverage
          
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
