name: CI

on:
    push:
      branches:
        - main
        - master
      tags:
        - '*'
    pull_request:
    workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist/
  
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install module
        run: |
          pip install .

      - name: Start containers
        run: docker compose -f "docker-compose.yml" up -d
      
      - name: Wait for containers to start
        run: python ./CI/wait_for_server.py

      - name: Run tests
        run: hatch test --cover

      - name: Generate reports
        run: |
          coverage xml -o ./report/coverage.xml
          coverage html -d ./report/html
          genbadge coverage -i ./report/coverage.xml -o ./report/badge.svg

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: ./report

      - name: Stop containers
        if: always()
        run: docker compose -f "docker-compose.yml" down
  
  publish-coverage:
     runs-on: ubuntu-latest
     needs: test
     steps:
      - uses: actions/download-artifact@v3
        with:
          name: report
      
      - name: List files
        run: ls -R

      - name: Upload coverage to branch
        uses: s0/git-publish-subdir-action@develop
        env:
            REPO: self
            BRANCH: coverage
            FOLDER: ./
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}